version: 2.1.1

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
  configuration: documentation/source/conf.py

python:
  install:
    - requirements: documentation/source/requirements.txt