from library.analyses.equations.linear import linear
from library.analyses.equations.quadratic import quadratic
from library.analyses.equations.cubic import cubic
from library.analyses.equations.hyperbolic import hyperbolic
from library.analyses.equations.exponential import exponential
from library.analyses.equations.logarithmic import logarithmic
from library.analyses.roots.linear import linear
from library.analyses.roots.quadratic import quadratic
from library.analyses.roots.cubic import cubic
from library.analyses.roots.hyperbolic import hyperbolic
from library.analyses.roots.exponential import exponential
from library.analyses.roots.logarithmic import logarithmic
from library.analyses.derivatives.linear import linear
from library.analyses.derivatives.quadratic import quadratic
from library.analyses.derivatives.cubic import cubic
from library.analyses.derivatives.hyperbolic import hyperbolic
from library.analyses.derivatives.exponential import exponential
from library.analyses.derivatives.logarithmic import logarithmic
from library.analyses.integrals.linear import linear
from library.analyses.integrals.quadratic import quadratic
from library.analyses.integrals.cubic import cubic
from library.analyses.integrals.hyperbolic import hyperbolic
from library.analyses.integrals.exponential import exponential
from library.analyses.integrals.logarithmic import logarithmic
from library.analyses.accumulation import accumulation
from library.analyses.critical_points import critical_points
from library.analyses.critical_values import critical_values
from library.analyses.decreasing import decreasing
from library.analyses.extrema import extrema
from library.analyses.increasing import increasing
from library.analyses.inflections import inflections
from library.analyses.intervals import intervals
from library.analyses.maxima import maxima
from library.analyses.mean_values import mean_value_derivative, mean_value_integral
from library.analyses.minima import minima