from library.statistics.correlation import correlation
from library.statistics.deviations import deviations
from library.statistics.maximum import maximum
from library.statistics.mean import mean
from library.statistics.median import median
from library.statistics.minimum import minimum
from library.statistics.quartiles import quartiles
from library.statistics.ranges import ranges
from library.statistics.residuals import residuals
from library.statistics.sort import sort